# Cloudflare Worker configuration for Stripe PaymentIntent creation
name = "stripe-payment-intent"
main = "stripe-payment-intent.js"
compatibility_date = "2024-01-01"

# Add your Stripe secret key as a secret in Cloudflare:
# wrangler secret put STRIPE_SECRET_KEY
# Or set it in Cloudflare Dashboard -> Workers & Pages -> Your Worker -> Settings -> Variables

[env.production]
vars = { }

[env.development]
vars = { }

